// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package v11

import "encoding/json"
import "fmt"
import "reflect"

// NodeInfo schema version 1.1.
type Nodeinfo struct {
	// Free form key value pairs for software specific values. Clients should not rely
	// on any specific key present.
	Metadata NodeinfoMetadata `json:"metadata" yaml:"metadata" mapstructure:"metadata"`

	// Whether this server allows open self-registration.
	OpenRegistrations bool `json:"openRegistrations" yaml:"openRegistrations" mapstructure:"openRegistrations"`

	// The protocols supported on this server.
	Protocols NodeinfoProtocols `json:"protocols" yaml:"protocols" mapstructure:"protocols"`

	// The third party sites this server can connect to via their application API.
	Services NodeinfoServices `json:"services" yaml:"services" mapstructure:"services"`

	// Metadata about server software in use.
	Software NodeinfoSoftware `json:"software" yaml:"software" mapstructure:"software"`

	// Usage statistics for this server.
	Usage NodeinfoUsage `json:"usage" yaml:"usage" mapstructure:"usage"`

	// The schema version, must be 1.1.
	Version NodeinfoVersion `json:"version" yaml:"version" mapstructure:"version"`
}

// Free form key value pairs for software specific values. Clients should not rely
// on any specific key present.
type NodeinfoMetadata map[string]interface{}

// The protocols supported on this server.
type NodeinfoProtocols struct {
	// The protocols this server can receive traffic for.
	Inbound []NodeinfoProtocolsInboundElem `json:"inbound" yaml:"inbound" mapstructure:"inbound"`

	// The protocols this server can generate traffic for.
	Outbound []NodeinfoProtocolsOutboundElem `json:"outbound" yaml:"outbound" mapstructure:"outbound"`
}

type NodeinfoProtocolsInboundElem string

const NodeinfoProtocolsInboundElemBuddycloud NodeinfoProtocolsInboundElem = "buddycloud"
const NodeinfoProtocolsInboundElemDiaspora NodeinfoProtocolsInboundElem = "diaspora"
const NodeinfoProtocolsInboundElemFriendica NodeinfoProtocolsInboundElem = "friendica"
const NodeinfoProtocolsInboundElemGnusocial NodeinfoProtocolsInboundElem = "gnusocial"
const NodeinfoProtocolsInboundElemLibertree NodeinfoProtocolsInboundElem = "libertree"
const NodeinfoProtocolsInboundElemMediagoblin NodeinfoProtocolsInboundElem = "mediagoblin"
const NodeinfoProtocolsInboundElemPumpio NodeinfoProtocolsInboundElem = "pumpio"
const NodeinfoProtocolsInboundElemRedmatrix NodeinfoProtocolsInboundElem = "redmatrix"
const NodeinfoProtocolsInboundElemSmtp NodeinfoProtocolsInboundElem = "smtp"
const NodeinfoProtocolsInboundElemTent NodeinfoProtocolsInboundElem = "tent"
const NodeinfoProtocolsInboundElemZot NodeinfoProtocolsInboundElem = "zot"

type NodeinfoProtocolsOutboundElem string

const NodeinfoProtocolsOutboundElemBuddycloud NodeinfoProtocolsOutboundElem = "buddycloud"
const NodeinfoProtocolsOutboundElemDiaspora NodeinfoProtocolsOutboundElem = "diaspora"
const NodeinfoProtocolsOutboundElemFriendica NodeinfoProtocolsOutboundElem = "friendica"
const NodeinfoProtocolsOutboundElemGnusocial NodeinfoProtocolsOutboundElem = "gnusocial"
const NodeinfoProtocolsOutboundElemLibertree NodeinfoProtocolsOutboundElem = "libertree"
const NodeinfoProtocolsOutboundElemMediagoblin NodeinfoProtocolsOutboundElem = "mediagoblin"
const NodeinfoProtocolsOutboundElemPumpio NodeinfoProtocolsOutboundElem = "pumpio"
const NodeinfoProtocolsOutboundElemRedmatrix NodeinfoProtocolsOutboundElem = "redmatrix"
const NodeinfoProtocolsOutboundElemSmtp NodeinfoProtocolsOutboundElem = "smtp"
const NodeinfoProtocolsOutboundElemTent NodeinfoProtocolsOutboundElem = "tent"
const NodeinfoProtocolsOutboundElemZot NodeinfoProtocolsOutboundElem = "zot"

// The third party sites this server can connect to via their application API.
type NodeinfoServices struct {
	// The third party sites this server can retrieve messages from for combined
	// display with regular traffic.
	Inbound []NodeinfoServicesInboundElem `json:"inbound" yaml:"inbound" mapstructure:"inbound"`

	// The third party sites this server can publish messages to on the behalf of a
	// user.
	Outbound []NodeinfoServicesOutboundElem `json:"outbound" yaml:"outbound" mapstructure:"outbound"`
}

type NodeinfoServicesInboundElem string

const NodeinfoServicesInboundElemAppnet NodeinfoServicesInboundElem = "appnet"
const NodeinfoServicesInboundElemGnusocial NodeinfoServicesInboundElem = "gnusocial"
const NodeinfoServicesInboundElemPumpio NodeinfoServicesInboundElem = "pumpio"

type NodeinfoServicesOutboundElem string

const NodeinfoServicesOutboundElemAppnet NodeinfoServicesOutboundElem = "appnet"
const NodeinfoServicesOutboundElemBlogger NodeinfoServicesOutboundElem = "blogger"
const NodeinfoServicesOutboundElemBuddycloud NodeinfoServicesOutboundElem = "buddycloud"
const NodeinfoServicesOutboundElemDiaspora NodeinfoServicesOutboundElem = "diaspora"
const NodeinfoServicesOutboundElemDreamwidth NodeinfoServicesOutboundElem = "dreamwidth"
const NodeinfoServicesOutboundElemDrupal NodeinfoServicesOutboundElem = "drupal"
const NodeinfoServicesOutboundElemFacebook NodeinfoServicesOutboundElem = "facebook"
const NodeinfoServicesOutboundElemFriendica NodeinfoServicesOutboundElem = "friendica"
const NodeinfoServicesOutboundElemGnusocial NodeinfoServicesOutboundElem = "gnusocial"
const NodeinfoServicesOutboundElemGoogle NodeinfoServicesOutboundElem = "google"
const NodeinfoServicesOutboundElemInsanejournal NodeinfoServicesOutboundElem = "insanejournal"
const NodeinfoServicesOutboundElemLibertree NodeinfoServicesOutboundElem = "libertree"
const NodeinfoServicesOutboundElemLinkedin NodeinfoServicesOutboundElem = "linkedin"
const NodeinfoServicesOutboundElemLivejournal NodeinfoServicesOutboundElem = "livejournal"
const NodeinfoServicesOutboundElemMediagoblin NodeinfoServicesOutboundElem = "mediagoblin"
const NodeinfoServicesOutboundElemMyspace NodeinfoServicesOutboundElem = "myspace"
const NodeinfoServicesOutboundElemPinterest NodeinfoServicesOutboundElem = "pinterest"
const NodeinfoServicesOutboundElemPosterous NodeinfoServicesOutboundElem = "posterous"
const NodeinfoServicesOutboundElemPumpio NodeinfoServicesOutboundElem = "pumpio"
const NodeinfoServicesOutboundElemRedmatrix NodeinfoServicesOutboundElem = "redmatrix"
const NodeinfoServicesOutboundElemSmtp NodeinfoServicesOutboundElem = "smtp"
const NodeinfoServicesOutboundElemTent NodeinfoServicesOutboundElem = "tent"
const NodeinfoServicesOutboundElemTumblr NodeinfoServicesOutboundElem = "tumblr"
const NodeinfoServicesOutboundElemTwitter NodeinfoServicesOutboundElem = "twitter"
const NodeinfoServicesOutboundElemWordpress NodeinfoServicesOutboundElem = "wordpress"
const NodeinfoServicesOutboundElemXmpp NodeinfoServicesOutboundElem = "xmpp"

// Metadata about server software in use.
type NodeinfoSoftware struct {
	// The canonical name of this server software.
	Name NodeinfoSoftwareName `json:"name" yaml:"name" mapstructure:"name"`

	// The version of this server software.
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

type NodeinfoSoftwareName string

const NodeinfoSoftwareNameDiaspora NodeinfoSoftwareName = "diaspora"
const NodeinfoSoftwareNameFriendica NodeinfoSoftwareName = "friendica"
const NodeinfoSoftwareNameHubzilla NodeinfoSoftwareName = "hubzilla"
const NodeinfoSoftwareNameRedmatrix NodeinfoSoftwareName = "redmatrix"

// Usage statistics for this server.
type NodeinfoUsage struct {
	// The amount of comments that were made by users that are registered on this
	// server.
	LocalComments *int `json:"localComments,omitempty" yaml:"localComments,omitempty" mapstructure:"localComments,omitempty"`

	// The amount of posts that were made by users that are registered on this server.
	LocalPosts *int `json:"localPosts,omitempty" yaml:"localPosts,omitempty" mapstructure:"localPosts,omitempty"`

	// statistics about the users of this server.
	Users NodeinfoUsageUsers `json:"users" yaml:"users" mapstructure:"users"`
}

// statistics about the users of this server.
type NodeinfoUsageUsers struct {
	// The amount of users that signed in at least once in the last 180 days.
	ActiveHalfyear *int `json:"activeHalfyear,omitempty" yaml:"activeHalfyear,omitempty" mapstructure:"activeHalfyear,omitempty"`

	// The amount of users that signed in at least once in the last 30 days.
	ActiveMonth *int `json:"activeMonth,omitempty" yaml:"activeMonth,omitempty" mapstructure:"activeMonth,omitempty"`

	// The total amount of on this server registered users.
	Total *int `json:"total,omitempty" yaml:"total,omitempty" mapstructure:"total,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NodeinfoProtocolsOutboundElem) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NodeinfoProtocolsOutboundElem {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NodeinfoProtocolsOutboundElem, v)
	}
	*j = NodeinfoProtocolsOutboundElem(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NodeinfoProtocolsInboundElem) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NodeinfoProtocolsInboundElem {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NodeinfoProtocolsInboundElem, v)
	}
	*j = NodeinfoProtocolsInboundElem(v)
	return nil
}

var enumValues_NodeinfoSoftwareName = []interface{}{
	"diaspora",
	"friendica",
	"hubzilla",
	"redmatrix",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NodeinfoSoftwareName) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NodeinfoSoftwareName {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NodeinfoSoftwareName, v)
	}
	*j = NodeinfoSoftwareName(v)
	return nil
}

var enumValues_NodeinfoProtocolsOutboundElem = []interface{}{
	"buddycloud",
	"diaspora",
	"friendica",
	"gnusocial",
	"libertree",
	"mediagoblin",
	"pumpio",
	"redmatrix",
	"smtp",
	"tent",
	"zot",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Nodeinfo) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["metadata"]; !ok || v == nil {
		return fmt.Errorf("field metadata in Nodeinfo: required")
	}
	if v, ok := raw["openRegistrations"]; !ok || v == nil {
		return fmt.Errorf("field openRegistrations in Nodeinfo: required")
	}
	if v, ok := raw["protocols"]; !ok || v == nil {
		return fmt.Errorf("field protocols in Nodeinfo: required")
	}
	if v, ok := raw["services"]; !ok || v == nil {
		return fmt.Errorf("field services in Nodeinfo: required")
	}
	if v, ok := raw["software"]; !ok || v == nil {
		return fmt.Errorf("field software in Nodeinfo: required")
	}
	if v, ok := raw["usage"]; !ok || v == nil {
		return fmt.Errorf("field usage in Nodeinfo: required")
	}
	if v, ok := raw["version"]; !ok || v == nil {
		return fmt.Errorf("field version in Nodeinfo: required")
	}
	type Plain Nodeinfo
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = Nodeinfo(plain)
	return nil
}

var enumValues_NodeinfoProtocolsInboundElem = []interface{}{
	"buddycloud",
	"diaspora",
	"friendica",
	"gnusocial",
	"libertree",
	"mediagoblin",
	"pumpio",
	"redmatrix",
	"smtp",
	"tent",
	"zot",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NodeinfoSoftware) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["name"]; !ok || v == nil {
		return fmt.Errorf("field name in NodeinfoSoftware: required")
	}
	if v, ok := raw["version"]; !ok || v == nil {
		return fmt.Errorf("field version in NodeinfoSoftware: required")
	}
	type Plain NodeinfoSoftware
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = NodeinfoSoftware(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NodeinfoServices) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["inbound"]; !ok || v == nil {
		return fmt.Errorf("field inbound in NodeinfoServices: required")
	}
	if v, ok := raw["outbound"]; !ok || v == nil {
		return fmt.Errorf("field outbound in NodeinfoServices: required")
	}
	type Plain NodeinfoServices
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = NodeinfoServices(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NodeinfoServicesOutboundElem) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NodeinfoServicesOutboundElem {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NodeinfoServicesOutboundElem, v)
	}
	*j = NodeinfoServicesOutboundElem(v)
	return nil
}

var enumValues_NodeinfoServicesOutboundElem = []interface{}{
	"appnet",
	"blogger",
	"buddycloud",
	"diaspora",
	"dreamwidth",
	"drupal",
	"facebook",
	"friendica",
	"gnusocial",
	"google",
	"insanejournal",
	"libertree",
	"linkedin",
	"livejournal",
	"mediagoblin",
	"myspace",
	"pinterest",
	"posterous",
	"pumpio",
	"redmatrix",
	"smtp",
	"tent",
	"tumblr",
	"twitter",
	"wordpress",
	"xmpp",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NodeinfoProtocols) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["inbound"]; !ok || v == nil {
		return fmt.Errorf("field inbound in NodeinfoProtocols: required")
	}
	if v, ok := raw["outbound"]; !ok || v == nil {
		return fmt.Errorf("field outbound in NodeinfoProtocols: required")
	}
	type Plain NodeinfoProtocols
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if len(plain.Inbound) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "inbound", 1)
	}
	if len(plain.Outbound) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "outbound", 1)
	}
	*j = NodeinfoProtocols(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NodeinfoUsage) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["users"]; !ok || v == nil {
		return fmt.Errorf("field users in NodeinfoUsage: required")
	}
	type Plain NodeinfoUsage
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = NodeinfoUsage(plain)
	return nil
}

type NodeinfoVersion string

var enumValues_NodeinfoVersion = []interface{}{
	"1.1",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NodeinfoVersion) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NodeinfoVersion {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NodeinfoVersion, v)
	}
	*j = NodeinfoVersion(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NodeinfoServicesInboundElem) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NodeinfoServicesInboundElem {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NodeinfoServicesInboundElem, v)
	}
	*j = NodeinfoServicesInboundElem(v)
	return nil
}

const NodeinfoVersionA11 NodeinfoVersion = "1.1"

var enumValues_NodeinfoServicesInboundElem = []interface{}{
	"appnet",
	"gnusocial",
	"pumpio",
}
