// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Defines values for CrawlStatus.
const (
	Failed   CrawlStatus = "failed"
	Finished CrawlStatus = "finished"
	Pending  CrawlStatus = "pending"
	Running  CrawlStatus = "running"
)

// Defines values for ServerStatus.
const (
	Offline ServerStatus = "offline"
	Online  ServerStatus = "online"
	Unknown ServerStatus = "unknown"
)

// Crawl defines model for Crawl.
type Crawl struct {
	ActiveUsersHalfYear *int32             `json:"active_users_half_year,omitempty"`
	ActiveUsersMonth    *int32             `json:"active_users_month,omitempty"`
	Error               *string            `json:"error,omitempty"`
	FinishedAt          time.Time          `json:"finished_at"`
	Id                  openapi_types.UUID `json:"id"`
	LocalComments       *int32             `json:"local_comments,omitempty"`
	LocalPosts          *int32             `json:"local_posts,omitempty"`
	NumberOfPeers       *int32             `json:"number_of_peers,omitempty"`
	ServerId            openapi_types.UUID `json:"server_id"`
	StartedAt           time.Time          `json:"started_at"`
	Status              CrawlStatus        `json:"status"`
	TotalUsers          *int32             `json:"total_users,omitempty"`
}

// CrawlStatus defines model for Crawl.Status.
type CrawlStatus string

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Server defines model for Server.
type Server struct {
	ActiveUsersHalfYear *int32             `json:"active_users_half_year,omitempty"`
	ActiveUsersMonth    *int32             `json:"active_users_month,omitempty"`
	Description         *string            `json:"description,omitempty"`
	Domain              string             `json:"domain"`
	Id                  openapi_types.UUID `json:"id"`
	LocalComments       *int32             `json:"local_comments,omitempty"`
	LocalPosts          *int32             `json:"local_posts,omitempty"`
	NumberOfPeers       *int32             `json:"number_of_peers,omitempty"`
	OpenRegistrations   *bool              `json:"open_registrations,omitempty"`
	Software            *string            `json:"software,omitempty"`
	Status              ServerStatus       `json:"status"`
	TotalUsers          *int32             `json:"total_users,omitempty"`
	Version             *string            `json:"version,omitempty"`
}

// ServerStatus defines model for Server.Status.
type ServerStatus string

// ListServersParams defines parameters for ListServers.
type ListServersParams struct {
	// Software filter by software name.
	Software *string `form:"software,omitempty" json:"software,omitempty"`

	// Page page number of results to return
	Page *int32 `form:"page,omitempty" json:"page,omitempty"`

	// PerPage number of results to return per page
	PerPage *int32 `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// ListCrawlsForServerParams defines parameters for ListCrawlsForServer.
type ListCrawlsForServerParams struct {
	// Page page number of results to return
	Page *int32 `form:"page,omitempty" json:"page,omitempty"`

	// PerPage number of results to return per page
	PerPage *int32 `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all servers
	// (GET /servers)
	ListServers(ctx echo.Context, params ListServersParams) error
	// Info for a specific server
	// (GET /servers/{id})
	GetServerByID(ctx echo.Context, id openapi_types.UUID) error
	// List all crawls for a server
	// (GET /servers/{id}/crawls)
	ListCrawlsForServer(ctx echo.Context, id openapi_types.UUID, params ListCrawlsForServerParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListServers converts echo context to params.
func (w *ServerInterfaceWrapper) ListServers(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListServersParams
	// ------------- Optional query parameter "software" -------------

	err = runtime.BindQueryParameter("form", true, false, "software", ctx.QueryParams(), &params.Software)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter software: %s", err))
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ListServers(ctx, params)
	return err
}

// GetServerByID converts echo context to params.
func (w *ServerInterfaceWrapper) GetServerByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetServerByID(ctx, id)
	return err
}

// ListCrawlsForServer converts echo context to params.
func (w *ServerInterfaceWrapper) ListCrawlsForServer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCrawlsForServerParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ListCrawlsForServer(ctx, id, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/servers", wrapper.ListServers)
	router.GET(baseURL+"/servers/:id", wrapper.GetServerByID)
	router.GET(baseURL+"/servers/:id/crawls", wrapper.ListCrawlsForServer)

}

type ListServersRequestObject struct {
	Params ListServersParams
}

type ListServersResponseObject interface {
	VisitListServersResponse(w http.ResponseWriter) error
}

type ListServers200JSONResponse struct {
	Page    int32    `json:"page"`
	PerPage int32    `json:"per_page"`
	Results []Server `json:"results"`
	Total   int64    `json:"total"`
}

func (response ListServers200JSONResponse) VisitListServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListServersdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListServersdefaultJSONResponse) VisitListServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetServerByIDRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetServerByIDResponseObject interface {
	VisitGetServerByIDResponse(w http.ResponseWriter) error
}

type GetServerByID200JSONResponse Server

func (response GetServerByID200JSONResponse) VisitGetServerByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetServerByIDdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetServerByIDdefaultJSONResponse) VisitGetServerByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListCrawlsForServerRequestObject struct {
	Id     openapi_types.UUID `json:"id"`
	Params ListCrawlsForServerParams
}

type ListCrawlsForServerResponseObject interface {
	VisitListCrawlsForServerResponse(w http.ResponseWriter) error
}

type ListCrawlsForServer200JSONResponse struct {
	Page    int32   `json:"page"`
	PerPage int32   `json:"per_page"`
	Results []Crawl `json:"results"`
	Total   int64   `json:"total"`
}

func (response ListCrawlsForServer200JSONResponse) VisitListCrawlsForServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListCrawlsForServerdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListCrawlsForServerdefaultJSONResponse) VisitListCrawlsForServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all servers
	// (GET /servers)
	ListServers(ctx context.Context, request ListServersRequestObject) (ListServersResponseObject, error)
	// Info for a specific server
	// (GET /servers/{id})
	GetServerByID(ctx context.Context, request GetServerByIDRequestObject) (GetServerByIDResponseObject, error)
	// List all crawls for a server
	// (GET /servers/{id}/crawls)
	ListCrawlsForServer(ctx context.Context, request ListCrawlsForServerRequestObject) (ListCrawlsForServerResponseObject, error)
}

type StrictHandlerFunc = runtime.StrictEchoHandlerFunc
type StrictMiddlewareFunc = runtime.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListServers operation middleware
func (sh *strictHandler) ListServers(ctx echo.Context, params ListServersParams) error {
	var request ListServersRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListServers(ctx.Request().Context(), request.(ListServersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListServers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListServersResponseObject); ok {
		return validResponse.VisitListServersResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// GetServerByID operation middleware
func (sh *strictHandler) GetServerByID(ctx echo.Context, id openapi_types.UUID) error {
	var request GetServerByIDRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetServerByID(ctx.Request().Context(), request.(GetServerByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetServerByID")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetServerByIDResponseObject); ok {
		return validResponse.VisitGetServerByIDResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// ListCrawlsForServer operation middleware
func (sh *strictHandler) ListCrawlsForServer(ctx echo.Context, id openapi_types.UUID, params ListCrawlsForServerParams) error {
	var request ListCrawlsForServerRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListCrawlsForServer(ctx.Request().Context(), request.(ListCrawlsForServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCrawlsForServer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListCrawlsForServerResponseObject); ok {
		return validResponse.VisitListCrawlsForServerResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYTW/cNhD9KwTbo7La2EUPOjVN3GKBoAng3gxjMZZGK6biR4YjrxfG/veCFLXaD9ne",
	"oD24RW60yBm+mTdvhutHWVrtrEHDXhaP0pcNaojL9wTrNiwcWYfECuNnKFnd47LzSH7ZQFsvNwgUdmpL",
	"GlgWUhm+vJCZ5I3D/k9cIcltdmisreHmTEMksvGStOWZlFmFnVoZ5RuslsHDnq8KGN+w0jj6G41UdXC2",
	"61Q1day1JbTL0mo95OcMqL2Rs/5sC9PpO6SlrZcOkc618kj3SMszQ/EMxN+YJc/AXYSDptOyuJEOTRU2",
	"M0mdMf1qICAsQbVYydsJX2wZ2p74s+LbZpLwa6cIq3BxDGqM+CCewxrYwR5R2LsvWHJAcTWU0WFNl7bC",
	"M7Ou0XtY4UQpHiGOPsfzU2iuYzyvRWIV+pKUY2XNpNAqq0FNb/0f5GQdmiXhSnkmCEnwe6HeWdsimCgK",
	"W/MaCCcTcaqYzvxl7NrITFrTKhNKwtZ1XP0bMsnkPZKfpmxKQonEZ0QSzJSpba8Lw1DGjoEaVCsLCU4x",
	"gv7Fr2G1QpopKzNpQAcX1/038e7zQvyJoGUmOwpGDbMr8nzP5rje5DvhQbsWozE3wKLz6AUIh+zZEgrw",
	"AozAh/4YW1GhtiayhaJG4I7QC2UENyg+OTTB0+VsLrzDUtWqjKzKTLaqROMjgQn4Owdlg+JiNj+A7Is8",
	"X6/XM4jbM0urPNn6/OPi/dUf11dvLmbzWcO6jeQhaf+pDrJWJU7FnccjeSBScbufs88pTLnHqJzP3s7m",
	"Q3GCU7KQl/FTJh1wE0sk77tiXK8wchV6SQx2UclCflSer9OZYEegkaPBzeMRCbVqGUncbcRQ5SJkaCYz",
	"mfIuC6nBs61iJkM7kF87pM1YBDt9ZOkx8YRQNtFZKHC5zY6BOFih6HUsbC0IfdeyD6QTckdP3R3MDu6t",
	"sIauZVm8zU61pJVROqj07dT4OYb0DBrhkES6exIW0vJpaJfzKWzwkLDN5y8gvQ0y986GsgyOL+bzQbto",
	"Yj2Ac20q//yL73vFCORw9rg03M7oPLuwzjue0hZOK0YdFz8S1rKQP+TjKzRPT9A8TcftzhcQwWbXJI9v",
	"/fmnl18RA4TBRTZUzC6U6X54UpzKAGMlIqJQEoMG49nE6zdQ8Fwa+ifLBIzO4IPDMuDAdCaTvtMaaJNk",
	"L6BtR2zbbNcs8kdVbZ/sGL9jahi/bhYfXuoZiw8hAaHn9r6DLGrkshnEEDrVqIU4hUZOmDrcV8ULb4h/",
	"XOznFNxpqlNkw82vieaFqa2oLQnYzblExCnheRl+0j0/KeKvPv+bpZSNV8X+9znxfU6cKKf/P8V/Ykwk",
	"/b3GKdFDGzrJXifcPS9vHo+exsPLfLb3vr2/kNvb7d8BAAD//3zKYTdWEgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
