package models

// Package models contains the models for the application logic.
// Different from the db models generated by sqlc.
// This avoids coupling the orchestrator and the crawler to the db models.

import (
	nodeinfo "github.com/cyclimse/fediverse-blahaj/pkg/nodeinfo/unversioned"
)

func ServerFromNodeInfo(domain string, peers []string, n nodeinfo.Nodeinfo) FediverseServer {
	return FediverseServer{
		Domain:            domain,
		Peers:             peers,
		SoftwareName:      n.GetSoftwareName(),
		OpenRegistrations: n.IsRegistrationOpen(),
		TotalUsers:        n.TotalUsers(),
		ActiveHalfyear:    n.ActiveUsersHalfyear(),
		ActiveMonth:       n.ActiveUsersMonth(),
		LocalPosts:        n.LocalPosts(),
		LocalComments:     n.LocalComments(),
	}
}

type FediverseServer struct {
	Domain string
	Peers  []string

	SoftwareName string

	OpenRegistrations bool
	TotalUsers        *int
	ActiveHalfyear    *int
	ActiveMonth       *int
	LocalPosts        *int
	LocalComments     *int
}

func (s FediverseServer) String() string {
	return s.Domain
}
