package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/cyclimse/fediverse-blahaj/internal/graph/model"
)

// Servers is the resolver for the servers field.
func (r *serverQueryResolver) Servers(ctx context.Context) ([]*model.Server, error) {
	panic(fmt.Errorf("not implemented: Servers - servers"))
}

// Server is the resolver for the server field.
func (r *serverQueryResolver) Server(ctx context.Context, id string) (*model.Server, error) {
	panic(fmt.Errorf("not implemented: Server - server"))
}

// CrawlExecutions is the resolver for the crawlExecutions field.
func (r *serverQueryResolver) CrawlExecutions(ctx context.Context) ([]*model.CrawlExecution, error) {
	panic(fmt.Errorf("not implemented: CrawlExecutions - crawlExecutions"))
}

// CrawlExecution is the resolver for the crawlExecution field.
func (r *serverQueryResolver) CrawlExecution(ctx context.Context, id string) (*model.CrawlExecution, error) {
	panic(fmt.Errorf("not implemented: CrawlExecution - crawlExecution"))
}

// ServerQuery returns ServerQueryResolver implementation.
func (r *Resolver) ServerQuery() ServerQueryResolver { return &serverQueryResolver{r} }

type serverQueryResolver struct{ *Resolver }
